wasm_api:
    resource: "@WasmApiBundle/Controller"
    prefix: /
    type: annotation
    # This will make exceptions return JSON instead of HTML
    defaults:
        _format: json

wasm_form:
    resource: "@WasmFormBundle/Controller"
    prefix: /
    type: annotation
    # This will make exceptions return JSON instead of HTML
    defaults:
        _format: json

wasm_boot:
    resource: "@WasmBootBundle/Controller"
    prefix: /
    type: annotation
    # This will make exceptions return JSON instead of HTML
    defaults:
        _format: json

wasm_cmf:
    resource: "@WasmCmfBundle/Controller"
    prefix: /
    type: annotation
    # This will make exceptions return JSON instead of HTML
    defaults:
        _format: json